[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GOOGLE_MAPS_API_KEY = "AIzaSyAVdAZdO0tjOSoNImELNfi5HtZVzitN3Y4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200