[build]
builder = "dockerfile"

[deploy]
startCommand = "/docker-entrypoint.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"