[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = "3000"

[variables]
# These will be set via Railway dashboard
# GOOGLE_MAPS_API_KEY = ""
# CORS_ORIGIN = ""
# RATE_LIMIT_WINDOW_MS = "900000"
# RATE_LIMIT_MAX_REQUESTS = "100"
# DEFAULT_SEARCH_RADIUS = "1000"
# MAX_SEARCH_RADIUS = "10000"
# RESULTS_PER_CATEGORY = "10"